apiVersion: v1
kind: Secret
metadata:
  name: mindmark-postgres-secret
type: Opaque
data:
  database: bWluZG1hcms=
  user: bWluZG1hcmstc2VydmVy
  password: dXNKZ1hDLUBFdENmNHhoMlRN

---
apiVersion: v1
kind: Service
metadata:
  name: mindmark-postgres
  labels:
    app: mindmark
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: mindmark

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mindmark-postgres-pv
  labels:
    type: local
    app: mindmark
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/mindmark-postgres-db"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mindmark-postgres-pvc
  labels:
    app: mindmark
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mindmark-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mindmark
  template:
    metadata:
      labels:
        app: mindmark
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: mindmark-postgres-secret
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: mindmark-postgres-secret
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mindmark-postgres-secret
                  key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-db
      volumes:
        - name: postgres-db
          persistentVolumeClaim:
            claimName: mindmark-postgres-pvc
