name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module: [backend, webapp]

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: |
          docker build -f ${{ matrix.module }}.Dockerfile -t mindmark-${{ matrix.module }}:latest "."

      - name: Publish
        run: |
          docker tag mindmark-${{ matrix.module }}:latest registry.blackrocksoul.pw/mindmark-${{ matrix.module }}:latest
          docker login https://registry.blackrocksoul.pw -u black -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
          docker image push registry.blackrocksoul.pw/mindmark-${{ matrix.module }}:latest

  sync:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Sync ArgoCD
        uses: omegion/argocd-actions@v1
        with:
          address: "argocd.blackrocksoul.pw"
          token: ${{ secrets.ARGOCD_TOKEN }}
          action: sync
          appName: "mind-mark"
